model: 
  fs: 8000
  nperseg: 256
  nfft: 256
  noverlap: 192
  window: 'hamming'
  time_frames: 8
  phase_aware: False
  batch_size: 512
  epochs: 50
  random: True
  use_true_normalization: False

dataset:
  noise_list: ['Babble']
  SNR_list: [0]
  buff_mult: 200

testID: 'Test1'